def menu_message(): # options system 
    print("+" + "-" * 35 + "+")
    print(f"| {"BANK DEPOSIT":^22}|" + f"{"1":^11}|")
    print("+" + "-" * 35 + "+")
    print(f"| {"BAND WITHDRAWAL":^22}|" + f"{"2":^11}|")
    print("+" + "-" * 35 + "+")
    print(f"| {"BANK STATEMENT":^22}|" + f"{"3":^11}|")
    print("+" + "-" * 35 + "+")
    print(f"| {"GO OUT":^22}|" + f"{"0":^11}|")
    print("+" + "-" * 35 + "+")
